import Foundation

struct DevotionData {
    static let monthlyThemes: [Int: String] = [
        1: "January – Faith & Trust in God",
        2: "February – Love (God, Others, Enemies, Self)",
        3: "March – Forgiveness & Grace",
        4: "April – Humility & Surrender",
        5: "May – Service & Sacrifice",
        6: "June – Faith & Obedience",
        7: "July – The Power of the Holy Spirit",
        8: "August – The Power of Prayer",
        9: "September – Faith Over Fear",
        10: "October – Boldness in Christ / Evangelism",
        11: "November – Peace & Patience",
        12: "December – The Life of Christ & Preparing Our Hearts"
    ]
    
    static let devotions: [Devotion] = [
        // January – Faith & Trust in God
        Devotion(month: 1, day: 1, verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5-6", task: "Write down 3 areas in your life where you feel uncertain. Pray and hand them over to God."),
        Devotion(month: 1, day: 2, verse: "Faith is the assurance of things hoped for…", reference: "Hebrews 11:1", task: "Create a bold prayer list. Ask for something that feels too big, but trust God for it anyway."),
        Devotion(month: 1, day: 3, verse: "Seek first the kingdom of God…", reference: "Matthew 6:33", task: "Begin your day tomorrow with 10 minutes of Scripture before checking your phone or emails."),
        Devotion(month: 1, day: 4, verse: "Fear not, for I am with you…", reference: "Isaiah 41:10", task: "Write this verse on a sticky note or your phone lock screen. Every time fear creeps in today, recite it aloud."),
        Devotion(month: 1, day: 5, verse: "All things work together for good…", reference: "Romans 8:28", task: "Reflect on a past hardship that God used for good. Journal what He taught you through it."),
        Devotion(month: 1, day: 6, verse: "But when you ask, you must believe and not doubt…", reference: "James 1:6", task: "Think of a prayer you’ve been hesitant to pray boldly. Pray it again — this time with full belief."),
        Devotion(month: 1, day: 7, verse: "Be still and know that I am God…", reference: "Psalm 46:10", task: "Spend 10 minutes today in complete silence. Sit in God's presence — no agenda, just listen."),
        Devotion(month: 1, day: 8, verse: "I believe; help my unbelief!", reference: "Mark 9:24", task: "Identify a specific doubt or fear. Ask Jesus directly to help your unbelief."),
        Devotion(month: 1, day: 9, verse: "Blessed is the one who trusts in the Lord…", reference: "Jeremiah 17:7", task: "Share this verse with a friend today who needs encouragement. Send a prayer with it."),
        Devotion(month: 1, day: 10, verse: "Do not be anxious about anything…", reference: "Philippians 4:6", task: "Take 5 minutes to write down your top 3 worries. Then, pray over each one, surrendering them to God."),
        Devotion(month: 1, day: 11, verse: "Commit your way to the Lord; trust in Him…", reference: "Psalm 37:5", task: "Write out your goals for this year, then lay them before God in prayer and surrender."),
        Devotion(month: 1, day: 12, verse: "We walk by faith, not by sight…", reference: "2 Corinthians 5:7", task: "Do one small act of faith today — even if it scares you. Let obedience lead, not comfort."),
        Devotion(month: 1, day: 13, verse: "The Lord is my strength and my shield…", reference: "Psalm 28:7", task: "Reflect on a time when God protected you. Thank Him specifically for His shield."),
        Devotion(month: 1, day: 14, verse: "You keep him in perfect peace whose mind is stayed on You…", reference: "Isaiah 26:3", task: "For 3 minutes, speak peace over your thoughts. Meditate on this verse in silence."),
        Devotion(month: 1, day: 15, verse: "May the God of hope fill you with all joy and peace in believing…", reference: "Romans 15:13", task: "Pray this verse over yourself and one person in your life who needs hope."),
        Devotion(month: 1, day: 16, verse: "Do not let your hearts be troubled. Believe in God…", reference: "John 14:1", task: "Identify what is troubling your heart today. Write it down and say, “God, I give this to You.”"),
        Devotion(month: 1, day: 17, verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1", task: "Make a list of things you're grateful for. Thank God for His provision."),
        Devotion(month: 1, day: 18, verse: "Cast all your anxiety on Him because He cares for you.", reference: "1 Peter 5:7", task: "Physically write your burdens on a paper. Tear it up as a symbol of giving them to God."),
        Devotion(month: 1, day: 19, verse: "For nothing will be impossible with God.", reference: "Luke 1:37", task: "Think of one “impossible” situation. Pray with boldness for breakthrough."),
        Devotion(month: 1, day: 20, verse: "Those who know your name trust in You…", reference: "Psalm 9:10", task: "Learn one new name of God today (e.g. Jehovah Jireh). Meditate on what it means."),
        Devotion(month: 1, day: 21, verse: "When you pass through the waters, I will be with you…", reference: "Isaiah 43:2", task: "Write down what storm you're in. Write beside it: “But God is with me.”"),
        Devotion(month: 1, day: 22, verse: "If you have faith as small as a mustard seed…", reference: "Matthew 17:20", task: "Draw a small seed. Under it, write one bold thing you're believing God for this year."),
        Devotion(month: 1, day: 23, verse: "Be strong and courageous. Do not be afraid…", reference: "Joshua 1:9", task: "Face one fear today — even if it’s small. Step out in trust."),
        Devotion(month: 1, day: 24, verse: "Though He slay me, yet will I trust Him.", reference: "Job 13:15", task: "Reflect on one area where God has said “wait” or “no.” Declare your trust anyway."),
        Devotion(month: 1, day: 25, verse: "When I am afraid, I put my trust in You.", reference: "Psalm 56:3", task: "Whisper this verse when fear rises. Use it as a prayer mantra throughout your day."),
        Devotion(month: 1, day: 26, verse: "He will never leave you nor forsake you.", reference: "Deuteronomy 31:6", task: "Write a short letter to God thanking Him for always being near — even when others left."),
        Devotion(month: 1, day: 27, verse: "The Lord is good, a refuge in times of trouble.", reference: "Nahum 1:7", task: "Make a list of God’s past faithfulness in your life. Keep it in your Bible."),
        Devotion(month: 1, day: 28, verse: "The life I now live, I live by faith in the Son of God…", reference: "Galatians 2:20", task: "Choose one area where you can live less by fear and more by faith today."),
        Devotion(month: 1, day: 29, verse: "He is my refuge and my fortress…", reference: "Psalm 91:2", task: "Spend 5 minutes in quiet worship. Thank God for being your safe place."),
        Devotion(month: 1, day: 30, verse: "Blessed are those who have not seen and yet have believed.", reference: "John 20:29", task: "Journal about one thing you're believing God for — without having seen the outcome yet."),
        Devotion(month: 1, day: 31, verse: "His mercies are new every morning…", reference: "Lamentations 3:22-23", task: "Reflect on this month. Write down the biggest area where your faith has grown."),

        // February – Love (God, Others, Enemies, Self)
        Devotion(month: 2, day: 1, verse: "If I speak in the tongues of men or of angels, but do not have love, I am only a resounding gong…", reference: "1 Corinthians 13:1", task: "Call or message someone just to say you're thankful for them — no agenda, just love."),
        Devotion(month: 2, day: 2, verse: "Love the Lord your God… and love your neighbor as yourself.", reference: "Matthew 22:37-39", task: "Make a list of three people you can serve this week. Pray for each of them by name today."),
        Devotion(month: 2, day: 3, verse: "A new command I give you: Love one another. As I have loved you…", reference: "John 13:34", task: "Do one act of kindness today for someone who doesn’t expect it."),
        Devotion(month: 2, day: 4, verse: "We love because He first loved us.", reference: "1 John 4:19", task: "Write a journal entry on how God’s love has shown up in your life recently."),
        Devotion(month: 2, day: 5, verse: "While we were still sinners, Christ died for us.", reference: "Romans 5:8", task: "Think of someone you’re struggling to love. Pray for them genuinely today."),
        Devotion(month: 2, day: 6, verse: "Love your enemies, do good to those who hate you.", reference: "Luke 6:27", task: "Forgive someone you haven’t yet forgiven. Start with, “God, help me to release them.”"),
        Devotion(month: 2, day: 7, verse: "Let us not love with words or speech but with actions and in truth.", reference: "1 John 3:18", task: "Show love through action today — no words. Just do something loving."),
        Devotion(month: 2, day: 8, verse: "Walk in the way of love, just as Christ loved us…", reference: "Ephesians 5:2", task: "Reflect on how Christ’s love was sacrificial. Ask God to show you where you’re being selfish."),
        Devotion(month: 2, day: 9, verse: "Put on love, which binds them all together in perfect unity.", reference: "Colossians 3:14", task: "Choose peace in a small conflict today. Love doesn’t always need to win — it reconciles."),
        Devotion(month: 2, day: 10, verse: "A friend loves at all times…", reference: "Proverbs 17:17", task: "Send a message to a friend you haven’t spoken to in a while. Remind them you’re still there."),
        Devotion(month: 2, day: 11, verse: "Greater love has no one than this: to lay down one’s life for one’s friends.", reference: "John 15:13", task: "Offer help to someone today, even if it’s inconvenient."),
        Devotion(month: 2, day: 12, verse: "Love is patient, love is kind…", reference: "1 Corinthians 13:4", task: "Pick one of love’s traits (patience, kindness, etc.). Practice it intentionally today."),
        Devotion(month: 2, day: 13, verse: "The fruit of the Spirit is love…", reference: "Galatians 5:22", task: "Do a 'love audit' — How has love shown in your speech, actions, and thoughts this week?"),
        Devotion(month: 2, day: 14, verse: "Many waters cannot quench love…", reference: "Song of Solomon 8:7", task: "If you’re in a relationship, speak life into your partner. If not, speak life into a friend or family member today."),
        Devotion(month: 2, day: 15, verse: "Love your enemies and pray for those who persecute you.", reference: "Matthew 5:44", task: "List the name of someone you find hard to love. Pray a blessing over their life."),
        Devotion(month: 2, day: 16, verse: "Whoever does not love does not know God, because God is love.", reference: "1 John 4:8", task: "Sit in silence and meditate on this one truth: God is love. Journal what comes up."),
        Devotion(month: 2, day: 17, verse: "Do not seek revenge or bear a grudge… but love your neighbor as yourself.", reference: "Leviticus 19:18", task: "Let go of one grudge today. Pray, “God, replace resentment with love.”"),
        Devotion(month: 2, day: 18, verse: "Love does no harm to a neighbor…", reference: "Romans 13:10", task: "Apologize to someone if you've hurt them — even if unintentionally. Make peace."),
        Devotion(month: 2, day: 19, verse: "[Love] is not easily angered…", reference: "1 Corinthians 13:5", task: "Pay attention to your emotions today. Ask God to help you respond in love, not react in anger."),
        Devotion(month: 2, day: 20, verse: "Be completely humble and gentle; be patient, bearing with one another in love.", reference: "Ephesians 4:2", task: "Show extra patience with someone who normally tests it."),
        Devotion(month: 2, day: 21, verse: "Love… with all your heart, soul, strength, and mind…", reference: "Luke 10:27", task: "Schedule 15 minutes today to spend fully focused on God — no distractions, just worship or prayer."),
        Devotion(month: 2, day: 22, verse: "Love covers a multitude of sins.", reference: "1 Peter 4:8", task: "Choose not to bring up someone’s past mistake today. Extend grace silently."),
        Devotion(month: 2, day: 23, verse: "He will rejoice over you with singing…", reference: "Zephaniah 3:17", task: "Reflect on the fact that God delights in you. Let His love heal any self-doubt or shame."),
        Devotion(month: 2, day: 24, verse: "What does the Lord require of you? To act justly and to love mercy…", reference: "Micah 6:8", task: "Tip someone generously. Do something kind that costs you something."),
        Devotion(month: 2, day: 25, verse: "See what great love the Father has lavished on us…", reference: "1 John 3:1", task: "Take 10 minutes today just to say thank you to God. Speak it, don’t just think it."),
        Devotion(month: 2, day: 26, verse: "Love your neighbor as yourself.", reference: "Mark 12:31", task: "Do something today that you wish someone would do for you."),
        Devotion(month: 2, day: 27, verse: "[Love] always protects, always trusts…", reference: "1 Corinthians 13:7", task: "Encourage someone today who feels alone or rejected. Your words matter."),
        Devotion(month: 2, day: 28, verse: "For God so loved the world…", reference: "John 3:16", task: "Meditate on the cross today. Thank Jesus specifically for what His love cost Him."),

        // March – Forgiveness & Grace
        Devotion(month: 3, day: 1, verse: "In Him we have redemption through His blood, the forgiveness of sins…", reference: "Ephesians 1:7", task: "Confess one sin you've been carrying in silence. Accept God's forgiveness — it's already done."),
        Devotion(month: 3, day: 2, verse: "Forgive as the Lord forgave you.", reference: "Colossians 3:13", task: "Write down the name of someone you need to forgive. Pray, “God, help me release this.”"),
        Devotion(month: 3, day: 3, verse: "As far as the east is from the west, so far has He removed our sins…", reference: "Psalm 103:12", task: "Reflect on how far God has brought you. Thank Him for not defining you by your past."),
        Devotion(month: 3, day: 4, verse: "Forgive us our debts, as we also have forgiven…", reference: "Matthew 6:12", task: "Think of someone who has hurt you. Write a short prayer for them, even if it’s hard."),
        Devotion(month: 3, day: 5, verse: "There is now no condemnation for those in Christ…", reference: "Romans 8:1", task: "Write down something you feel ashamed of. Burn, tear, or delete it. You are not condemned."),
        Devotion(month: 3, day: 6, verse: "Forgive, and you will be forgiven.", reference: "Luke 6:37", task: "Offer forgiveness today to someone — even if they never asked for it."),
        Devotion(month: 3, day: 7, verse: "Though your sins are like scarlet, they shall be white as snow…", reference: "Isaiah 1:18", task: "Meditate for 5 minutes on God’s mercy. Say aloud: “I am clean because of Jesus.”"),
        Devotion(month: 3, day: 8, verse: "If we confess our sins, He is faithful and just to forgive…", reference: "1 John 1:9", task: "Confess one thing to God you've been holding back. He already knows. Let Him lift it off of you."),
        Devotion(month: 3, day: 9, verse: "How many times shall I forgive? …Seventy times seven.", reference: "Matthew 18:21-22", task: "Forgive again. Even if you already did. Say it again. Release again."),
        Devotion(month: 3, day: 10, verse: "You do not stay angry forever but delight to show mercy.", reference: "Micah 7:18", task: "Do something merciful today — help someone who 'doesn't deserve it.'"),
        Devotion(month: 3, day: 11, verse: "He saved us… not because of righteous things we had done…", reference: "Titus 3:5", task: "Reflect on how God loved you even when you weren’t lovable. Now show that love to someone else."),
        Devotion(month: 3, day: 12, verse: "For I will forgive their wickedness and remember their sins no more.", reference: "Hebrews 8:12", task: "Stop replaying that failure in your mind. Forgiveness means God doesn’t bring it up — so neither should you."),
        Devotion(month: 3, day: 13, verse: "Blessed are the merciful, for they will be shown mercy.", reference: "Matthew 5:7", task: "Find someone who made a mistake (online, in person, etc.) — respond with grace instead of judgment."),
        Devotion(month: 3, day: 14, verse: "My grace is sufficient for you…", reference: "2 Corinthians 12:9", task: "Where do you feel weak or unworthy? Ask God to meet you there with grace."),
        Devotion(month: 3, day: 15, verse: "Create in me a clean heart, O God…", reference: "Psalm 51:10", task: "Journal a prayer asking God to clean your heart from resentment, bitterness, or hidden sin."),
        Devotion(month: 3, day: 16, verse: "Whoever covers an offense seeks love…", reference: "Proverbs 17:9", task: "Let someone off the hook today — forgive without needing to be right."),
        Devotion(month: 3, day: 17, verse: "Where sin increased, grace increased all the more.", reference: "Romans 5:20", task: "Reflect on where you’ve fallen short. Now double that with how much grace God has given you."),
        Devotion(month: 3, day: 18, verse: "If you hold anything against anyone, forgive them…", reference: "Mark 11:25", task: "Text or call someone you’ve distanced yourself from. Reopen the door — even if just a little."),
        Devotion(month: 3, day: 19, verse: "If You kept a record of sins… who could stand?", reference: "Psalm 130:3-4", task: "Think about the mercy God has shown you. Offer that same mercy to someone today."),
        Devotion(month: 3, day: 20, verse: "You are a gracious and compassionate God…", reference: "Jonah 4:2", task: "Give compassion today where you normally give judgment — even if just in your thoughts."),
        Devotion(month: 3, day: 21, verse: "His mercies are new every morning…", reference: "Lamentations 3:22-23", task: "Wake up tomorrow and declare: “God’s mercy is new for me today.” Say it out loud."),
        Devotion(month: 3, day: 22, verse: "Mercy triumphs over judgment.", reference: "James 2:13", task: "Don’t bring up someone’s failure today — not to them, not behind their back, not even in your mind."),
        Devotion(month: 3, day: 23, verse: "Neither do I condemn you… go and sin no more.", reference: "John 8:11", task: "Imagine Jesus saying this to you personally. Let that freedom change how you live today."),
        Devotion(month: 3, day: 24, verse: "Restore gently…", reference: "Galatians 6:1", task: "Reach out to someone who’s messed up. Offer encouragement instead of correction."),
        Devotion(month: 3, day: 25, verse: "The Lord, slow to anger, abounding in love…", reference: "Exodus 34:6", task: "Pause before reacting today. Practice being slow to anger."),
        Devotion(month: 3, day: 26, verse: "It is by grace you have been saved…", reference: "Ephesians 2:8-9", task: "Spend time worshiping God today — not for what you’ve done, but for what He’s done for you."),
        Devotion(month: 3, day: 27, verse: "Let them turn to the Lord… for He will freely pardon.", reference: "Isaiah 55:7", task: "Ask God to forgive one thing you’ve been too embarrassed to pray about."),
        Devotion(month: 3, day: 28, verse: "I have taken away your sin, and I will put fine garments on you.", reference: "Zechariah 3:4", task: "Visualize God clothing you in righteousness today. Walk like you're forgiven — not guilty."),
        Devotion(month: 3, day: 29, verse: "Unless you forgive… from your heart.", reference: "Matthew 18:35", task: "Don’t just say you forgive — mean it. Ask God to help if your heart isn’t there yet."),
        Devotion(month: 3, day: 30, verse: "I acknowledged my sin… and You forgave me.", reference: "Psalm 32:5", task: "Write an honest confession prayer. Let it be raw. God meets you in truth."),
        Devotion(month: 3, day: 31, verse: "Whoever has been forgiven much loves much.", reference: "Luke 7:47", task: "Reflect on how much God has forgiven you. Now let that fuel how you love others going forward."),

        // April – Humility & Surrender
        Devotion(month: 4, day: 1, verse: "Humble yourselves before the Lord, and He will lift you up.", reference: "James 4:10", task: "Ask God today, “Where am I relying too much on myself?” Write down what comes to mind."),
        Devotion(month: 4, day: 2, verse: "Not my will, but Yours be done.", reference: "Luke 22:42", task: "Identify one area of your life where you’re still trying to stay in control. Surrender it in prayer."),
        Devotion(month: 4, day: 3, verse: "Do nothing out of selfish ambition or vain conceit. Rather, in humility, value others above yourselves.", reference: "Philippians 2:3", task: "Today, let someone else go first — in line, in traffic, in conversation."),
        Devotion(month: 4, day: 4, verse: "With humility comes wisdom.", reference: "Proverbs 11:2", task: "Ask a friend or mentor for honest feedback today. Receive it without defending yourself."),
        Devotion(month: 4, day: 5, verse: "Those who exalt themselves will be humbled, and those who humble themselves will be exalted.", reference: "Matthew 23:12", task: "Give someone else credit today, even if you contributed too."),
        Devotion(month: 4, day: 6, verse: "Walk humbly with your God.", reference: "Micah 6:8", task: "Take a walk today without your phone. Reflect on how small you are — and how big God is."),
        Devotion(month: 4, day: 7, verse: "He must increase, but I must decrease.", reference: "John 3:30", task: "Post or share something today that glorifies God — not yourself."),
        Devotion(month: 4, day: 8, verse: "Do not think of yourself more highly than you ought.", reference: "Romans 12:3", task: "Compliment someone today in an area you might secretly compete with them in."),
        Devotion(month: 4, day: 9, verse: "Humble yourselves under God’s mighty hand, that He may lift you up in due time.", reference: "1 Peter 5:6", task: "Let go of striving. Do your best today without trying to force outcomes."),
        Devotion(month: 4, day: 10, verse: "These are the ones I look on with favor: those who are humble and contrite in spirit…", reference: "Isaiah 66:2", task: "Kneel in prayer today. Physically take a posture of humility before God."),
        Devotion(month: 4, day: 11, verse: "A broken and contrite heart You, God, will not despise.", reference: "Psalm 51:17", task: "Write God a confession letter. Be honest. He honors your raw heart."),
        Devotion(month: 4, day: 12, verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3", task: "Serve someone who can’t repay you today. Do it anonymously if possible."),
        Devotion(month: 4, day: 13, verse: "Let not the wise boast of their wisdom… but let the one who boasts boast about this: that they understand and know Me…", reference: "Jeremiah 9:23-24", task: "Instead of talking about your achievements today, share what God has done in your life."),
        Devotion(month: 4, day: 14, verse: "I have been crucified with Christ and I no longer live, but Christ lives in me.", reference: "Galatians 2:20", task: "Ask God, “What needs to die in me today so that You can live through me?”"),
        Devotion(month: 4, day: 15, verse: "Take My yoke upon you and learn from Me, for I am gentle and humble in heart…", reference: "Matthew 11:29", task: "Study the humility of Jesus. Read Philippians 2:5–8 and reflect on how you can imitate it."),
        Devotion(month: 4, day: 16, verse: "Humility is the fear of the Lord; its wages are riches and honor and life.", reference: "Proverbs 22:4", task: "Today, speak less in conversation and listen more. Humility begins with listening."),
        Devotion(month: 4, day: 17, verse: "He guides the humble in what is right and teaches them His way.", reference: "Psalm 25:9", task: "Ask God for direction in one area of your life. Write down what you sense."),
        Devotion(month: 4, day: 18, verse: "If My people… humble themselves and pray…", reference: "2 Chronicles 7:14", task: "Spend 15 minutes in uninterrupted prayer today. Come with no agenda, just surrender."),
        Devotion(month: 4, day: 19, verse: "All those who exalt themselves will be humbled…", reference: "Luke 14:11", task: "Celebrate someone else's success today. Speak well of them publicly."),
        Devotion(month: 4, day: 20, verse: "I live… with the one who is contrite and lowly in spirit…", reference: "Isaiah 57:15", task: "Fast from something today — even if it's just social media or sugar — as an act of humility."),
        Devotion(month: 4, day: 21, verse: "Seek the Lord, all you humble… seek righteousness, seek humility…", reference: "Zephaniah 2:3", task: "Reflect on how humility isn’t weakness — it’s power under control. Where can you apply that?"),
        Devotion(month: 4, day: 22, verse: "Because your heart was responsive and you humbled yourself…", reference: "2 Kings 22:19", task: "Respond to correction with grace today — no defending, no excuses. Just receive."),
        Devotion(month: 4, day: 23, verse: "He humbled Himself by becoming obedient to death…", reference: "Philippians 2:8", task: "Do one task today that feels beneath you — without complaint."),
        Devotion(month: 4, day: 24, verse: "When people are brought low and you say, 'Lift them up!' then He will save the downcast.", reference: "Job 22:29", task: "Encourage someone today who seems discouraged. Your words may lift their spirit."),
        Devotion(month: 4, day: 25, verse: "Honor one another above yourselves.", reference: "Romans 12:10", task: "Brag on someone else today in public. Celebrate their character, not just accomplishments."),
        Devotion(month: 4, day: 26, verse: "Whoever wants to become great among you must be your servant.", reference: "Matthew 20:26", task: "Ask someone today: “How can I help you?” Then actually do it."),
        Devotion(month: 4, day: 27, verse: "I am unworthy of all the kindness and faithfulness You have shown…", reference: "Genesis 32:10", task: "Write down three undeserved blessings in your life and thank God for His grace."),
        Devotion(month: 4, day: 28, verse: "Let them show it by their good life, by deeds done in the humility that comes from wisdom.", reference: "James 3:13", task: "Let your humility show through actions today. Be intentional and unseen."),
        Devotion(month: 4, day: 29, verse: "God chose the lowly things of this world… so that no one may boast before Him.", reference: "1 Corinthians 1:28-29", task: "Remind yourself: God doesn't need perfection — just surrender."),
        Devotion(month: 4, day: 30, verse: "The Lord crowns the humble with victory.", reference: "Psalm 149:4", task: "Reflect on how far you've come this month. What has humility taught you?"),

        // May – Service & Sacrifice
        Devotion(month: 5, day: 1, verse: "For even the Son of Man did not come to be served, but to serve.", reference: "Mark 10:45", task: "Do one thing today that benefits someone else and costs you time."),
        Devotion(month: 5, day: 2, verse: "Greater love has no one than this: to lay down one's life for one's friends.", reference: "John 15:13", task: "Call or text a friend just to check in — without expecting anything in return."),
        Devotion(month: 5, day: 3, verse: "Offer your bodies as a living sacrifice, holy and pleasing to God.", reference: "Romans 12:1", task: "Deny yourself one comfort today (social media, snacks, etc.) and offer it to God."),
        Devotion(month: 5, day: 4, verse: "Serve one another humbly in love.", reference: "Galatians 5:13", task: "Clean something today — not for yourself, but for someone else."),
        Devotion(month: 5, day: 5, verse: "If anyone forces you to go one mile, go with them two miles.", reference: "Matthew 5:41", task: "Go above and beyond for someone today, especially if it’s inconvenient."),
        Devotion(month: 5, day: 6, verse: "Do not forget to do good and to share with others.", reference: "Hebrews 13:16", task: "Give something away today — your time, your food, or something valuable."),
        Devotion(month: 5, day: 7, verse: "Look not only to your own interests, but also to the interests of others.", reference: "Philippians 2:4", task: "Ask someone, “How can I support you this week?” and actually follow through."),
        Devotion(month: 5, day: 8, verse: "Give, and it will be given to you.", reference: "Luke 6:38", task: "Bless someone financially today — even if it’s just buying them a coffee."),
        Devotion(month: 5, day: 9, verse: "Do not withhold good from those to whom it is due.", reference: "Proverbs 3:27", task: "Write a thank you message to someone who’s impacted your life."),
        Devotion(month: 5, day: 10, verse: "If you spend yourselves… your light will rise in the darkness.", reference: "Isaiah 58:10", task: "Volunteer your time today — even if it’s just helping a neighbor or friend."),
        Devotion(month: 5, day: 11, verse: "Do not let your left hand know what your right hand is doing.", reference: "Matthew 6:3", task: "Do a secret act of kindness today — no one should know but God."),
        Devotion(month: 5, day: 12, verse: "We who are strong ought to bear with the failings of the weak.", reference: "Romans 15:1", task: "Be patient with someone difficult today. Offer grace instead of judgment."),
        Devotion(month: 5, day: 13, verse: "Let us not love with words or speech but with actions.", reference: "1 John 3:18", task: "Write down 3 practical ways you can show love today — and do one."),
        Devotion(month: 5, day: 14, verse: "Suppose a brother or sister is without clothes and daily food... what good is it?", reference: "James 2:15-16", task: "Donate to a food bank, clothing drive, or support someone in need."),
        Devotion(month: 5, day: 15, verse: "Whatever you did for one of the least of these, you did for Me.", reference: "Matthew 25:40", task: "Serve someone marginalized — the lonely, overlooked, or hurting."),
        Devotion(month: 5, day: 16, verse: "Carry each other’s burdens.", reference: "Galatians 6:2", task: "Pray with someone today — right then and there. Don’t wait."),
        Devotion(month: 5, day: 17, verse: "Now that I, your Lord, have washed your feet… you should also wash one another’s feet.", reference: "John 13:14", task: "Do a lowly task for someone today. Let it stretch your pride."),
        Devotion(month: 5, day: 18, verse: "He had compassion on them, because they were harassed and helpless.", reference: "Matthew 9:36", task: "Ask God to give you compassion for someone you usually overlook or avoid."),
        Devotion(month: 5, day: 19, verse: "It is more blessed to give than to receive.", reference: "Acts 20:35", task: "Give away something you value today — it can be physical or emotional."),
        Devotion(month: 5, day: 20, verse: "Use whatever gift you have received to serve others.", reference: "1 Peter 4:10", task: "Use your skill or talent today to bless someone — even in a small way."),
        Devotion(month: 5, day: 21, verse: "The Samaritan… took pity on him. He went to him and bandaged his wounds.", reference: "Luke 10:33-34", task: "Interrupt your plans to help someone today, like the Good Samaritan did."),
        Devotion(month: 5, day: 22, verse: "Freely you have received; freely give.", reference: "Matthew 10:8", task: "Give someone your time today — with no expectations or agenda."),
        Devotion(month: 5, day: 23, verse: "Share with the Lord’s people who are in need. Practice hospitality.", reference: "Romans 12:13", task: "Invite someone into your space — for coffee, a meal, or just conversation."),
        Devotion(month: 5, day: 24, verse: "Whatever you do, work at it with all your heart, as working for the Lord.", reference: "Colossians 3:23", task: "Do your daily work today like God is your boss. Give it excellence and joy."),
        Devotion(month: 5, day: 25, verse: "Whoever serves Me must follow Me.", reference: "John 12:26", task: "Follow a prompting from the Holy Spirit today — even if it doesn’t make sense."),
        Devotion(month: 5, day: 26, verse: "If I give all I possess to the poor… but do not have love, I gain nothing.", reference: "1 Corinthians 13:3", task: "Reflect: Is your service rooted in love, or obligation? Ask God to purify your motive."),
        Devotion(month: 5, day: 27, verse: "Then your Father, who sees what is done in secret, will reward you.", reference: "Matthew 6:4", task: "Do something kind today with no credit and no recognition."),
        Devotion(month: 5, day: 28, verse: "[Jesus] made Himself nothing… taking the very nature of a servant.", reference: "Philippians 2:7", task: "Ask God today, “How can I make myself nothing — so that You may be everything?”"),
        Devotion(month: 5, day: 29, verse: "Walk in the way of love, just as Christ loved us and gave Himself up for us.", reference: "Ephesians 5:2", task: "Sacrifice your own preferences today to bless someone else’s."),
        Devotion(month: 5, day: 30, verse: "God loves a cheerful giver.", reference: "2 Corinthians 9:7", task: "Give joyfully today — not reluctantly. Let giving be a celebration."),
        Devotion(month: 5, day: 31, verse: "Let us not grow weary in doing good.", reference: "Galatians 6:9", task: "Reflect on this month. Where did you serve well? Where can you grow?"),

        // June – Faith & Obedience
        Devotion(month: 6, day: 1, verse: "Now faith is confidence in what we hope for and assurance about what we do not see.", reference: "Hebrews 11:1", task: "Write down one thing you’re believing God for — and thank Him in advance."),
        Devotion(month: 6, day: 2, verse: "Faith by itself, if it is not accompanied by action, is dead.", reference: "James 2:17", task: "Take one bold action today that aligns with your faith — even if it’s scary."),
        Devotion(month: 6, day: 3, verse: "Faith comes by hearing, and hearing by the Word of God.", reference: "Romans 10:17", task: "Listen to Scripture today instead of music or podcasts."),
        Devotion(month: 6, day: 4, verse: "Trust in the Lord with all your heart… and He will make your paths straight.", reference: "Proverbs 3:5-6", task: "Surrender a situation you’ve been trying to control. Give it to God."),
        Devotion(month: 6, day: 5, verse: "Be strong and courageous. Do not be afraid… for the Lord your God is with you.", reference: "Joshua 1:9", task: "Do something today that requires courage in your faith."),
        Devotion(month: 6, day: 6, verse: "When I am afraid, I put my trust in You.", reference: "Psalm 56:3", task: "Journal about a current fear — and then pray it out loud to God."),
        Devotion(month: 6, day: 7, verse: "You will keep in perfect peace those whose minds are steadfast.", reference: "Isaiah 26:3", task: "Spend 10 minutes in stillness, meditating on God’s peace."),
        Devotion(month: 6, day: 8, verse: "If you love Me, keep My commandments.", reference: "John 14:15", task: "Reflect: What command of Jesus are you avoiding? Obey it today."),
        Devotion(month: 6, day: 9, verse: "Noah did everything just as God commanded him.", reference: "Genesis 6:22", task: "Obey God today in one area that feels inconvenient or unusual."),
        Devotion(month: 6, day: 10, verse: "Your word is a lamp for my feet, a light on my path.", reference: "Psalm 119:105", task: "Read one chapter of Proverbs today and write down the verse that guides you."),
        Devotion(month: 6, day: 11, verse: "Because you say so, I will let down the nets.", reference: "Luke 5:5", task: "Do something God has asked you to do — even if it didn’t work the first time."),
        Devotion(month: 6, day: 12, verse: "Faith as small as a mustard seed can move mountains.", reference: "Matthew 17:20", task: "Pray boldly today for a breakthrough — no matter how impossible it seems."),
        Devotion(month: 6, day: 13, verse: "To obey is better than sacrifice.", reference: "1 Samuel 15:22", task: "Choose obedience over spiritual performance today."),
        Devotion(month: 6, day: 14, verse: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7", task: "Take one action today based on trust in God — not logic or feelings."),
        Devotion(month: 6, day: 15, verse: "I live by faith in the Son of God.", reference: "Galatians 2:20", task: "Declare aloud today: “I live by faith — not fear, not doubt, not pride.”"),
        Devotion(month: 6, day: 16, verse: "Do not be anxious about anything… present your requests to God.", reference: "Philippians 4:6", task: "Turn every anxious thought today into a whispered prayer."),
        Devotion(month: 6, day: 17, verse: "Seek first the kingdom of God and His righteousness.", reference: "Matthew 6:33", task: "Make your first priority today spiritual — not physical."),
        Devotion(month: 6, day: 18, verse: "If you do not stand firm in your faith, you will not stand at all.", reference: "Isaiah 7:9", task: "Stand firm in one area today where you’re tempted to compromise."),
        Devotion(month: 6, day: 19, verse: "Taste and see that the Lord is good.", reference: "Psalm 34:8", task: "Reflect on a moment God proved His goodness to you. Thank Him out loud."),
        Devotion(month: 6, day: 20, verse: "Be strong and courageous… the Lord goes with you.", reference: "Deuteronomy 31:6", task: "Step into something new today with bold trust in God’s presence."),
        Devotion(month: 6, day: 21, verse: "Without faith it is impossible to please God.", reference: "Hebrews 11:6", task: "Ask yourself: Is this choice pleasing to God, or just comfortable for me?"),
        Devotion(month: 6, day: 22, verse: "Commit your way to the Lord; trust in Him and He will do this.", reference: "Psalm 37:5", task: "Write down one dream you commit to God today — and let Him guide the outcome."),
        Devotion(month: 6, day: 23, verse: "Do not merely listen to the word… Do what it says.", reference: "James 1:22", task: "Re-read a past verse from this month and act on it today."),
        Devotion(month: 6, day: 24, verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14", task: "Stop striving today. Be still. Let God handle what you’ve been trying to fix."),
        Devotion(month: 6, day: 25, verse: "He did not waver through unbelief… being fully persuaded God had power to do what He promised.", reference: "Romans 4:20-21", task: "Declare over a situation: “God is able. I trust Him.”"),
        Devotion(month: 6, day: 26, verse: "Blessed is the one who trusts in the Lord.", reference: "Jeremiah 17:7", task: "Say “yes” to something you’ve been hesitating on because of fear."),
        Devotion(month: 6, day: 27, verse: "The Lord is my shepherd; I lack nothing.", reference: "Psalm 23:1", task: "Reflect: Where have you been acting like God won’t provide? Surrender it."),
        Devotion(month: 6, day: 28, verse: "What is impossible with man is possible with God.", reference: "Luke 18:27", task: "Pray for something today that only God can do."),
        Devotion(month: 6, day: 29, verse: "Whether you turn… your ears will hear a voice behind you, saying, ‘This is the way; walk in it.’", reference: "Isaiah 30:21", task: "Ask God to guide one decision today. Listen for His leading."),
        Devotion(month: 6, day: 30, verse: "Blessed are those who have not seen and yet have believed.", reference: "John 20:29", task: "Trust God today without needing signs, confirmations, or visible results."),

        // July – The Power of the Holy Spirit
        Devotion(month: 7, day: 1, verse: "But you will receive power when the Holy Spirit comes on you...", reference: "Acts 1:8", task: "Ask God today for a fresh filling of the Holy Spirit — and expect it."),
        Devotion(month: 7, day: 2, verse: "For those who are led by the Spirit of God are the children of God.", reference: "Romans 8:14", task: "Before every decision today, pause and ask: “Holy Spirit, what would You have me do?”"),
        Devotion(month: 7, day: 3, verse: "Since we live by the Spirit, let us keep in step with the Spirit.", reference: "Galatians 5:25", task: "Take 5 minutes of silence. Ask God to speak to you through stillness."),
        Devotion(month: 7, day: 4, verse: "The Holy Spirit will teach you all things and remind you of everything I have said.", reference: "John 14:26", task: "Memorize one Bible verse today and invite the Spirit to remind you of it this week."),
        Devotion(month: 7, day: 5, verse: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.", reference: "2 Timothy 1:7", task: "Face one fear boldly today — trusting the Spirit’s power in you."),
        Devotion(month: 7, day: 6, verse: "Be filled with the Spirit.", reference: "Ephesians 5:18", task: "Say this aloud: “Holy Spirit, fill me again. I surrender everything.”"),
        Devotion(month: 7, day: 7, verse: "Your bodies are temples of the Holy Spirit.", reference: "1 Corinthians 6:19", task: "Treat your body with reverence today. Honor God with how you eat, speak, and rest."),
        Devotion(month: 7, day: 8, verse: "The fruit of the Spirit is love, joy, peace, patience...", reference: "Galatians 5:22-23", task: "Choose one fruit of the Spirit and intentionally display it today."),
        Devotion(month: 7, day: 9, verse: "All of them were filled with the Holy Spirit and began to speak in other tongues...", reference: "Acts 2:4", task: "If you're open, ask the Spirit for a new spiritual gift — and wait in expectation."),
        Devotion(month: 7, day: 10, verse: "The Spirit of Him who raised Jesus from the dead is living in you.", reference: "Romans 8:11", task: "Meditate on this truth: The resurrection power of Christ is in you."),
        Devotion(month: 7, day: 11, verse: "He will guide you into all the truth.", reference: "John 16:13", task: "Bring one area of confusion to the Spirit in prayer. Wait for clarity."),
        Devotion(month: 7, day: 12, verse: "These are the things God has revealed to us by his Spirit.", reference: "1 Corinthians 2:10", task: "Ask the Spirit to show you something deeper in today’s Scripture."),
        Devotion(month: 7, day: 13, verse: "Not by might nor by power, but by my Spirit,’ says the Lord.", reference: "Zechariah 4:6", task: "Stop striving. Let God take over something you've been forcing."),
        Devotion(month: 7, day: 14, verse: "Do not quench the Spirit.", reference: "1 Thessalonians 5:19", task: "Reflect: Have you ignored the Spirit’s nudge lately? Obey Him today."),
        Devotion(month: 7, day: 15, verse: "The Spirit of the Lord will rest on him—the Spirit of wisdom... understanding... counsel...", reference: "Isaiah 11:2", task: "Ask the Spirit for wisdom in one personal or professional decision today."),
        Devotion(month: 7, day: 16, verse: "While they were worshiping... the Holy Spirit said...", reference: "Acts 13:2", task: "Worship for 10 uninterrupted minutes today. Let the Spirit speak."),
        Devotion(month: 7, day: 17, verse: "Teach me to do Your will... may Your good Spirit lead me on level ground.", reference: "Psalm 143:10", task: "Surrender your will. Tell God: “I want Your way, not mine.”"),
        Devotion(month: 7, day: 18, verse: "I am filled with power— with the Spirit of the Lord...", reference: "Micah 3:8", task: "Speak life today with boldness, not fear. You are filled with power."),
        Devotion(month: 7, day: 19, verse: "Do not grieve the Holy Spirit of God.", reference: "Ephesians 4:30", task: "Reflect: Is there any ongoing sin you need to confess today?"),
        Devotion(month: 7, day: 20, verse: "The Spirit helps us in our weakness... intercedes for us with groans...", reference: "Romans 8:26", task: "When you don’t know what to pray today, sit in silence and let the Spirit intercede."),
        Devotion(month: 7, day: 21, verse: "Where the Spirit of the Lord is, there is freedom.", reference: "2 Corinthians 3:17", task: "Invite the Spirit into one area where you feel bound or stuck. Expect freedom."),
        Devotion(month: 7, day: 22, verse: "They were all filled with the Holy Spirit and spoke the word of God boldly.", reference: "Acts 4:31", task: "Share your faith today — even briefly — with someone God highlights."),
        Devotion(month: 7, day: 23, verse: "I will put my Spirit in you and move you to follow my decrees.", reference: "Ezekiel 36:27", task: "Ask the Spirit to empower your obedience today."),
        Devotion(month: 7, day: 24, verse: "Build yourselves up in your most holy faith and pray in the Holy Spirit.", reference: "Jude 1:20", task: "Set a timer and pray for 5 minutes straight — led by the Spirit."),
        Devotion(month: 7, day: 25, verse: "They were given rest by the Spirit of the Lord.", reference: "Isaiah 63:14", task: "Stop rushing. Rest deeply in God today. Take a Sabbath moment."),
        Devotion(month: 7, day: 26, verse: "Now to each one the manifestation of the Spirit is given for the common good.", reference: "1 Corinthians 12:7", task: "Use your spiritual gift — or serve someone — for their benefit today."),
        Devotion(month: 7, day: 27, verse: "Walk by the Spirit, and you will not gratify the desires of the flesh.", reference: "Galatians 5:16", task: "Say no to one temptation today — not in your strength, but in the Spirit’s."),
        Devotion(month: 7, day: 28, verse: "May the God of hope fill you with all joy and peace… by the power of the Holy Spirit.", reference: "Romans 15:13", task: "Choose joy today. Ask the Spirit to fill you with peace, even if circumstances don’t change."),
        Devotion(month: 7, day: 29, verse: "We have received... the Spirit who is from God, so that we may understand what God has freely given us.", reference: "1 Corinthians 2:12", task: "Spend time thanking God for everything He has freely given you in Christ."),
        Devotion(month: 7, day: 30, verse: "I will pour out my Spirit on your offspring...", reference: "Isaiah 44:3", task: "Pray for your children, future children, or the next generation to be Spirit-filled."),
        Devotion(month: 7, day: 31, verse: "Whoever has ears, let them hear what the Spirit says to the churches.", reference: "Revelation 2:7", task: "Ask the Spirit this: “What are You saying to me?” Write down the answer."),

        // August – The Power of Prayer
        Devotion(month: 8, day: 1, verse: "Pray without ceasing.", reference: "1 Thessalonians 5:17", task: "Whisper a short prayer every hour today, even just one sentence. Stay connected."),
        Devotion(month: 8, day: 2, verse: "Go into your room, close the door and pray to your Father...", reference: "Matthew 6:6", task: "Spend 10 private minutes in prayer — just you and God. No distractions."),
        Devotion(month: 8, day: 3, verse: "The prayer of a righteous person is powerful and effective.", reference: "James 5:16", task: "Boldly pray for something big today. Believe your voice moves heaven."),
        Devotion(month: 8, day: 4, verse: "In every situation, by prayer and petition… present your requests to God.", reference: "Philippians 4:6", task: "Make a prayer list of everything bothering you. Give it all to God."),
        Devotion(month: 8, day: 5, verse: "Very early in the morning… Jesus got up and prayed.", reference: "Mark 1:35", task: "Set your alarm 10 minutes earlier tomorrow. Give God the first words of your day."),
        Devotion(month: 8, day: 6, verse: "In the morning, Lord, you hear my voice.", reference: "Psalm 5:3", task: "Start your day with gratitude. Thank God for 5 things before checking your phone."),
        Devotion(month: 8, day: 7, verse: "Be joyful in hope, patient in affliction, faithful in prayer.", reference: "Romans 12:12", task: "Recommit to prayer — even when you feel nothing. Stay faithful."),
        Devotion(month: 8, day: 8, verse: "Always pray and never give up.", reference: "Luke 18:1", task: "Revisit a prayer you stopped praying. Bring it to God again with fresh faith."),
        Devotion(month: 8, day: 9, verse: "Call to me and I will answer you.", reference: "Jeremiah 33:3", task: "Ask God to speak to you clearly today — and listen."),
        Devotion(month: 8, day: 10, verse: "The Lord is near to all who call on him...", reference: "Psalm 145:18", task: "Pray out loud today, even for 60 seconds. Speak like He’s in the room — because He is."),
        Devotion(month: 8, day: 11, verse: "Pray in the Spirit on all occasions with all kinds of prayers...", reference: "Ephesians 6:18", task: "Try a new form of prayer today: journaling, singing, silence, or Scripture-based prayer."),
        Devotion(month: 8, day: 12, verse: "Ask and it will be given to you; seek and you will find.", reference: "Matthew 7:7", task: "Write a bold prayer request and place it somewhere visible. Pray it daily."),
        Devotion(month: 8, day: 13, verse: "Approach God’s throne of grace with confidence.", reference: "Hebrews 4:16", task: "Approach God boldly today. No fear. You are His child."),
        Devotion(month: 8, day: 14, verse: "Devote yourselves to prayer, being watchful and thankful.", reference: "Colossians 4:2", task: "Pause three times today to thank God for something specific."),
        Devotion(month: 8, day: 15, verse: "If I had cherished sin in my heart, the Lord would not have listened.", reference: "Psalm 66:18", task: "Confess one area of struggle honestly before God. He’s not surprised."),
        Devotion(month: 8, day: 16, verse: "Jesus often withdrew to lonely places and prayed.", reference: "Luke 5:16", task: "Go somewhere quiet today — even for 5 minutes. Just pray."),
        Devotion(month: 8, day: 17, verse: "The righteous cry out, and the Lord hears them.", reference: "Psalm 34:17", task: "Cry out. Pour out your heart like David did — raw, real, messy."),
        Devotion(month: 8, day: 18, verse: "The Lord delights in the prayers of the upright.", reference: "Proverbs 15:8", task: "Tell God what’s in your heart. Know that He delights in hearing you."),
        Devotion(month: 8, day: 19, verse: "This, then, is how you should pray…", reference: "Matthew 6:9-13", task: "Slowly pray the Lord’s Prayer, line by line, inserting your own thoughts between each line."),
        Devotion(month: 8, day: 20, verse: "I pray also for those who will believe in me...", reference: "John 17:20", task: "Intercede for someone else’s future today — their faith, their freedom, their calling."),
        Devotion(month: 8, day: 21, verse: "If we ask anything according to his will, he hears us.", reference: "1 John 5:14", task: "Ask God: “What is Your will?” before making any requests."),
        Devotion(month: 8, day: 22, verse: "Evening, morning and noon I cry out… and he hears.", reference: "Psalm 55:17", task: "Pray at all 3: morning, afternoon, evening. Set reminders if needed."),
        Devotion(month: 8, day: 23, verse: "Lord, teach us to pray.", reference: "Luke 11:1", task: "Ask God to deepen your prayer life. Surrender your routine and let Him shape it."),
        Devotion(month: 8, day: 24, verse: "I mourned and fasted and prayed before the God of heaven.", reference: "Nehemiah 1:4", task: "Skip one meal or comfort today and use that time to pray."),
        Devotion(month: 8, day: 25, verse: "From inside the fish Jonah prayed...", reference: "Jonah 2:1", task: "Even in mess or discomfort — pray. Talk to God from your “belly of the whale.”"),
        Devotion(month: 8, day: 26, verse: "About midnight Paul and Silas were praying and singing hymns...", reference: "Acts 16:25", task: "Worship in your prayer. Sing out loud to God — even briefly."),
        Devotion(month: 8, day: 27, verse: "Before they call I will answer...", reference: "Isaiah 65:24", task: "Thank God for answering prayers you haven’t even prayed yet."),
        Devotion(month: 8, day: 28, verse: "After Job prayed for his friends, the Lord restored his fortunes.", reference: "Job 42:10", task: "Pray for someone who’s wronged you. Bless them in prayer."),
        Devotion(month: 8, day: 29, verse: "He got down on his knees three times a day and prayed…", reference: "Daniel 6:10", task: "Try praying on your knees today. A change in posture can deepen reverence."),
        Devotion(month: 8, day: 30, verse: "May my prayer be set before you like incense...", reference: "Psalm 141:2", task: "Light a candle or create an atmosphere of worship as you pray. Let it be intentional."),
        Devotion(month: 8, day: 31, verse: "If you believe, you will receive whatever you ask for in prayer.", reference: "Matthew 21:22", task: "End the month by praying your boldest prayer yet — and believe."),

        // September – Faith Over Fear
        Devotion(month: 9, day: 1, verse: "Do not fear, for I am with you...", reference: "Isaiah 41:10", task: "Write down one fear and say aloud, “God is with me, I will not fear.”"),
        Devotion(month: 9, day: 2, verse: "God has not given us a spirit of fear, but of power...", reference: "2 Timothy 1:7", task: "Walk boldly today. Do one small thing you've been afraid to do — with God’s courage."),
        Devotion(month: 9, day: 3, verse: "Be strong and courageous… the Lord your God will be with you.", reference: "Joshua 1:9", task: "Post this verse somewhere you’ll see it often. Repeat it three times today."),
        Devotion(month: 9, day: 4, verse: "When I am afraid, I put my trust in you.", reference: "Psalm 56:3", task: "Pray about something you’re anxious about. Place it in God’s hands — fully."),
        Devotion(month: 9, day: 5, verse: "Trust in the Lord with all your heart...", reference: "Proverbs 3:5-6", task: "Make a list of areas where you're leaning on your own understanding. Pray over each one."),
        Devotion(month: 9, day: 6, verse: "But when he saw the wind, he was afraid…", reference: "Matthew 14:30", task: "Meditate for 2 minutes visualizing yourself walking on water — eyes fixed on Jesus."),
        Devotion(month: 9, day: 7, verse: "Peace I leave with you… Do not let your hearts be troubled.", reference: "John 14:27", task: "Turn off all screens for 10 minutes. Sit still. Invite God's peace in."),
        Devotion(month: 9, day: 8, verse: "You received the Spirit of adoption… by Him we cry, ‘Abba, Father.’", reference: "Romans 8:15", task: "Speak to God today as your Father. Trust Him like a child."),
        Devotion(month: 9, day: 9, verse: "I sought the Lord, and he answered me; he delivered me from all my fears.", reference: "Psalm 34:4", task: "Write a prayer asking God to deliver you from specific fears."),
        Devotion(month: 9, day: 10, verse: "Why are you so afraid? Do you still have no faith?", reference: "Mark 4:40", task: "Reflect on a time God came through for you. Journal it. Remind your fear who He is."),
        Devotion(month: 9, day: 11, verse: "Do not be afraid… the Lord your God goes with you.", reference: "Deuteronomy 31:6", task: "Choose one goal you’ve been delaying. Take a bold step toward it today."),
        Devotion(month: 9, day: 12, verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1", task: "Write this verse on a sticky note and place it on your bathroom mirror."),
        Devotion(month: 9, day: 13, verse: "The Lord is my helper; I will not be afraid.", reference: "Hebrews 13:6", task: "Say this aloud three times during a moment of anxiety today."),
        Devotion(month: 9, day: 14, verse: "Do not worry about tomorrow…", reference: "Matthew 6:34", task: "Fast from future thinking today. Focus only on this moment with God."),
        Devotion(month: 9, day: 15, verse: "Do not fear, for I have redeemed you; I have summoned you by name.", reference: "Isaiah 43:1", task: "Write your name after this verse. Personalize it. Read it aloud."),
        Devotion(month: 9, day: 16, verse: "Don’t be afraid; you are worth more than many sparrows.", reference: "Luke 12:7", task: "Ask God to reveal your worth in His eyes. Listen quietly for the answer."),
        Devotion(month: 9, day: 17, verse: "You will not fear the terror of night...", reference: "Psalm 91:5", task: "Before bed, read Psalm 91. Speak it as a declaration over your life."),
        Devotion(month: 9, day: 18, verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14", task: "Surrender one battle you're trying to fight alone. Let God take it."),
        Devotion(month: 9, day: 19, verse: "Do not be afraid… I am your shield.", reference: "Genesis 15:1", task: "Draw or imagine a physical shield. Visualize God protecting you today."),
        Devotion(month: 9, day: 20, verse: "I will trust and not be afraid.", reference: "Isaiah 12:2", task: "Repeat this declaration aloud 3x today: “I will trust and not be afraid.”"),
        Devotion(month: 9, day: 21, verse: "Even though I walk through the valley... I will fear no evil.", reference: "Psalm 23:4", task: "Walk outside or around your home while reciting this verse slowly."),
        Devotion(month: 9, day: 22, verse: "Do not be afraid of those who kill the body but cannot kill the soul.", reference: "Matthew 10:28", task: "Let go of people-pleasing. Pray for courage to stand boldly for your faith."),
        Devotion(month: 9, day: 23, verse: "He will quiet you with his love.", reference: "Zephaniah 3:17", task: "Play a soft worship song. Let God's love wash over your fears."),
        Devotion(month: 9, day: 24, verse: "Say to those with fearful hearts, 'Be strong, do not fear...'", reference: "Isaiah 35:4", task: "Encourage someone else today who is afraid. Speak faith into their heart."),
        Devotion(month: 9, day: 25, verse: "Cast all your anxiety on Him because He cares for you.", reference: "1 Peter 5:7", task: "Write down your top 3 worries. Physically tear the paper up as you pray over them."),
        Devotion(month: 9, day: 26, verse: "Take heart! I have overcome the world.", reference: "John 16:33", task: "Boldly thank Jesus for overcoming your biggest fear before you even face it."),
        Devotion(month: 9, day: 27, verse: "They will have no fear of bad news; their hearts are steadfast.", reference: "Psalm 112:7", task: "Choose not to feed fear today — no negative news, no worst-case thoughts."),
        Devotion(month: 9, day: 28, verse: "You will keep in perfect peace those whose minds are steadfast.", reference: "Isaiah 26:3", task: "Practice 5 minutes of stillness. Focus on God and His peace."),
        Devotion(month: 9, day: 29, verse: "Do not be afraid, Mary; you have found favor with God.", reference: "Luke 1:30", task: "Remember: fear doesn’t mean failure — it often precedes favor. Embrace the unknown."),
        Devotion(month: 9, day: 30, verse: "Do not be afraid. I am the First and the Last.", reference: "Revelation 1:17", task: "Celebrate how far you've come. End the month thanking God for carrying you through."),

        // October – Boldness in Christ / Evangelism
                // October – Boldness in Christ / Evangelism
                Devotion(month: 10, day: 1, verse: "For to us a child is born, to us a son is given…", reference: "Isaiah 9:6", task: "Sit in stillness for 3 minutes today. Whisper: “Thank You, Jesus, for coming for me.”"),
                Devotion(month: 10, day: 2, verse: "The Word became flesh and made his dwelling among us.", reference: "John 1:14", task: "Reflect: What does it mean to you that God became human? Journal your thoughts."),
                Devotion(month: 10, day: 3, verse: "Do not be afraid, Mary; you have found favor with God.", reference: "Luke 1:30", task: "Pray to respond to God’s plans like Mary — with trust, not fear."),
                Devotion(month: 10, day: 4, verse: "…you are to give him the name Jesus, because he will save his people from their sins.", reference: "Matthew 1:21", task: "Thank Jesus specifically for how He’s saved you. Name one area."),
                Devotion(month: 10, day: 5, verse: "…the virgin will conceive and give birth to a son, and will call him Immanuel.", reference: "Isaiah 7:14", task: "Say “God is with me” throughout the day. Let it anchor you."),
                Devotion(month: 10, day: 6, verse: "Blessed is she who has believed that the Lord would fulfill his promises to her!", reference: "Luke 1:45", task: "Revisit a promise you’re still waiting on. Speak belief over it."),
                Devotion(month: 10, day: 7, verse: "…out of you will come… one who will be ruler over Israel.", reference: "Micah 5:2", task: "Ask God to rule over your heart today. Surrender control."),
                Devotion(month: 10, day: 8, verse: "My soul magnifies the Lord, and my spirit rejoices in God my Savior.", reference: "Luke 1:46–47", task: "Write your own version of Mary’s praise — a song, a poem, or a prayer."),
                Devotion(month: 10, day: 9, verse: "When they saw the star, they rejoiced with exceeding great joy.", reference: "Matthew 2:10", task: "Look for small “stars” — signs of God’s goodness — and praise Him for them."),
                Devotion(month: 10, day: 10, verse: "…there was no room for them in the inn.", reference: "Luke 2:7", task: "Clear 10 minutes today to make “room” for Jesus — undistracted time."),
                Devotion(month: 10, day: 11, verse: "For nothing will be impossible with God.", reference: "Luke 1:37", task: "Bring an impossible prayer to God today. Speak it with boldness."),
                Devotion(month: 10, day: 12, verse: "Be still, and know that I am God.", reference: "Psalm 46:10", task: "Sit in quiet stillness. No music. No talking. Just awareness of God."),
                Devotion(month: 10, day: 13, verse: "Do not be afraid. I bring you good news that will cause great joy.", reference: "Luke 2:10", task: "What is one fear you can hand to Jesus today? Trade it for His joy."),
                Devotion(month: 10, day: 14, verse: "…he made himself nothing… taking the very nature of a servant.", reference: "Philippians 2:7", task: "Serve someone secretly today — just like Jesus did."),
                Devotion(month: 10, day: 15, verse: "They opened their treasures and presented him with gifts…", reference: "Matthew 2:11", task: "What can you give to Jesus this Christmas? Time? Praise? Change?"),
                Devotion(month: 10, day: 16, verse: "For God so loved the world that he gave his one and only Son…", reference: "John 3:16", task: "Thank God for loving you before you ever loved Him. Sit in that truth."),
                Devotion(month: 10, day: 17, verse: "Come, let us bow down in worship, let us kneel before the Lord our Maker.", reference: "Psalm 95:6", task: "Kneel in worship today — even if just for 30 seconds. Let your body respond in awe."),
                Devotion(month: 10, day: 18, verse: "May the God of hope fill you with all joy and peace…", reference: "Romans 15:13", task: "Ask God to flood your heart with His hope. Invite Him to fill what’s empty."),
                Devotion(month: 10, day: 19, verse: "I stand at the door and knock…", reference: "Revelation 3:20", task: "Imagine Jesus knocking. How would you welcome Him today?"),
                Devotion(month: 10, day: 20, verse: "He will take great delight in you… He will rejoice over you with singing.", reference: "Zephaniah 3:17", task: "Picture God singing over you. Receive His delight like a child."),
                Devotion(month: 10, day: 21, verse: "The Son is the radiance of God's glory…", reference: "Hebrews 1:3", task: "Step outside. Let the sunlight hit your face. Thank Jesus — the true Light."),
                Devotion(month: 10, day: 22, verse: "Thanks be to God for his indescribable gift!", reference: "2 Corinthians 9:15", task: "Write down the top 3 gifts Jesus has brought into your life."),
                Devotion(month: 10, day: 23, verse: "…and they will call him Immanuel (which means ‘God with us’).", reference: "Matthew 1:23", task: "Invite God into every part of your day — including errands, chores, and moments of stress."),
                Devotion(month: 10, day: 24, verse: "Glory to God in the highest, and on earth peace to those on whom his favor rests.", reference: "Luke 2:14", task: "Light a candle tonight and read Luke 2:1–20 aloud. Sit in wonder."),
                Devotion(month: 10, day: 25, verse: "Today… a Savior has been born to you; he is the Messiah, the Lord.", reference: "Luke 2:11", task: "Before any presents, give your worship to Jesus. Tell Him how much He means to you."),
                Devotion(month: 10, day: 26, verse: "He is before all things, and in him all things hold together.", reference: "Colossians 1:17", task: "As the year ends, thank Jesus for holding you together. Reflect on His faithfulness."),
                Devotion(month: 10, day: 27, verse: "There is a time for everything…", reference: "Ecclesiastes 3:1", task: "Ask God what season you’re in. What’s He doing in your life right now?"),
                Devotion(month: 10, day: 28, verse: "His mercies are new every morning.", reference: "Lamentations 3:22–23", task: "Look back at the past year. Where do you see God’s mercy the most?"),
                Devotion(month: 10, day: 29, verse: "In their hearts humans plan their course, but the Lord establishes their steps.", reference: "Proverbs 16:9", task: "Invite God into your plans for next year. Ask for His vision over your own."),
                Devotion(month: 10, day: 30, verse: "See, I am doing a new thing!", reference: "Isaiah 43:19", task: "Write down one area where you want to see God do something new next year."),
                Devotion(month: 10, day: 31, verse: "You crown the year with your bounty…", reference: "Psalm 65:11", task: "End the year with 10 minutes of praise. Rejoice for all that God has done — and all He will do."),

                // November – Peace & Patience
                Devotion(month: 11, day: 1, verse: "Give thanks in all circumstances; for this is God’s will for you in Christ Jesus.", reference: "1 Thessalonians 5:18", task: "Write down 3 things you’re grateful for — even if today is hard."),
                Devotion(month: 11, day: 2, verse: "I have learned to be content whatever the circumstances.", reference: "Philippians 4:11", task: "Pause today when you feel lack. Whisper: “God, You are enough.”"),
                Devotion(month: 11, day: 3, verse: "Give thanks to the Lord, for he is good; his love endures forever.", reference: "Psalm 107:1", task: "Meditate on one way God’s love has endured in your life. Thank Him for it."),
                Devotion(month: 11, day: 4, verse: "Every good and perfect gift is from above...", reference: "James 1:17", task: "Take inventory of the gifts God has given you this year — big and small."),
                Devotion(month: 11, day: 5, verse: "Be thankful.", reference: "Colossians 3:15", task: "Send a voice note or text to someone expressing genuine gratitude for who they are."),
                Devotion(month: 11, day: 6, verse: "Enter his gates with thanksgiving…", reference: "Psalm 100:4", task: "Begin your prayer today only with praise and gratitude — no requests."),
                Devotion(month: 11, day: 7, verse: "Be content with what you have, because God has said, ‘Never will I leave you.’", reference: "Hebrews 13:5", task: "Reflect: Where has discontentment stolen your peace? Give it back to God."),
                Devotion(month: 11, day: 8, verse: "One of them… came back, praising God… and gave thanks.", reference: "Luke 17:15–16", task: "Revisit a past prayer God answered. Go back and thank Him intentionally."),
                Devotion(month: 11, day: 9, verse: "…a cheerful heart has a continual feast.", reference: "Proverbs 15:15", task: "Smile more today — even if things are imperfect. Choose joy."),
                Devotion(month: 11, day: 10, verse: "You will be enriched… so that you can be generous.", reference: "2 Corinthians 9:11", task: "Give today — time, money, kindness — and do it with a grateful heart."),
                Devotion(month: 11, day: 11, verse: "I will give thanks to you, Lord, with all my heart.", reference: "Psalm 9:1", task: "Journal your thanks — pour your heart out like a personal love letter to God."),
                Devotion(month: 11, day: 12, verse: "Godliness with contentment is great gain.", reference: "1 Timothy 6:6", task: "Fast from complaining for 24 hours. Choose thankfulness every time."),
                Devotion(month: 11, day: 13, verse: "My heart leaps for joy, and with my song I praise him.", reference: "Psalm 28:7", task: "Sing or play worship music aloud today. Let your heart lift in praise."),
                Devotion(month: 11, day: 14, verse: "…that each of them may eat and drink, and find satisfaction in all their toil — this is the gift of God.", reference: "Ecclesiastes 3:13", task: "Thank God for your job, chores, or responsibilities — even the tiring ones."),
                Devotion(month: 11, day: 15, verse: "Praise the Lord, my soul, and forget not all his benefits.", reference: "Psalm 103:2", task: "Make a list titled: “10 Benefits of Walking with God.” Read it aloud."),
                Devotion(month: 11, day: 16, verse: "Always giving thanks to God the Father for everything…", reference: "Ephesians 5:20", task: "Thank God for something hard — and ask Him to reveal the hidden blessing in it."),
                Devotion(month: 11, day: 17, verse: "Give thanks to the Lord, for he is good. His love endures forever.", reference: "Psalm 136:1", task: "Repeat that verse throughout the day. Let it anchor you when you're stressed."),
                Devotion(month: 11, day: 18, verse: "You will keep in perfect peace those whose minds are steadfast.", reference: "Isaiah 26:3", task: "Thank God for peace today — and sit silently in His presence for 5 minutes."),
                Devotion(month: 11, day: 19, verse: "…overflowing with thankfulness.", reference: "Colossians 2:7", task: "Write a thank-you card or message to someone who helped you grow spiritually."),
                Devotion(month: 11, day: 20, verse: "…you clothed me with joy, that my heart may sing your praises.", reference: "Psalm 30:11–12", task: "Celebrate something small today — laughter, nature, friendship — as God's gift."),
                Devotion(month: 11, day: 21, verse: "Seek first his kingdom…", reference: "Matthew 6:33", task: "Ask yourself: “What am I truly chasing?” Let thankfulness redirect your focus."),
                Devotion(month: 11, day: 22, verse: "In all things God works for the good...", reference: "Romans 8:28", task: "Reflect on a past trial that became a blessing. Thank Him for His unseen hand."),
                Devotion(month: 11, day: 23, verse: "Give thanks to the Lord… his love endures forever.", reference: "1 Chronicles 16:34", task: "Before each meal today, pause longer. Reflect on how God has fed and sustained you."),
                Devotion(month: 11, day: 24, verse: "It is good to give thanks to the Lord.", reference: "Psalm 92:1", task: "Begin and end your day with a verbal “thank you” to God — no matter how it went."),
                Devotion(month: 11, day: 25, verse: "…with thanksgiving, present your requests to God.", reference: "Philippians 4:6", task: "Before asking for anything today, spend 2 full minutes listing what you're grateful for."),
                Devotion(month: 11, day: 26, verse: "Do not despise these small beginnings.", reference: "Zechariah 4:10", task: "Thank God for the small progress you’ve made — spiritually, emotionally, or physically."),
                Devotion(month: 11, day: 27, verse: "This is the day the Lord has made; let us rejoice and be glad in it.", reference: "Psalm 118:24", task: "Take a walk and thank God aloud for what you see, feel, and hear."),
                Devotion(month: 11, day: 28, verse: "The Lord gave and the Lord has taken away; blessed be the name of the Lord.", reference: "Job 1:21", task: "If you've lost something or someone, tell God you trust Him. Thank Him anyway."),
                Devotion(month: 11, day: 29, verse: "Give praise to the Lord, proclaim his name; make known what he has done.", reference: "Isaiah 12:4", task: "Share a testimony today — online or with someone — about God’s goodness in your life."),
                Devotion(month: 11, day: 30, verse: "They celebrate your abundant goodness and joyfully sing of your righteousness.", reference: "Psalm 145:7", task: "End the month with praise. Write your own Psalm of gratitude to God."),

                // December – Humility & Servanthood
                Devotion(month: 12, day: 1, verse: "In your relationships with one another, have the same mindset as Christ Jesus.", reference: "Philippians 2:5", task: "Ask yourself, “What would Jesus do in my interactions today?” Then model it."),
                Devotion(month: 12, day: 2, verse: "The Son of Man did not come to be served, but to serve.", reference: "Matthew 20:28", task: "Do one selfless act for someone today — without expecting recognition."),
                Devotion(month: 12, day: 3, verse: "Now that I, your Lord and Teacher, have washed your feet… you should wash one another’s feet.", reference: "John 13:14", task: "Find a way to “wash someone’s feet” — serve someone in a humble way today."),
                Devotion(month: 12, day: 4, verse: "Humility is the fear of the Lord; its wages are riches and honor and life.", reference: "Proverbs 22:4", task: "Choose humility today. Let someone else speak, go first, or win."),
                Devotion(month: 12, day: 5, verse: "Clothe yourselves with compassion, kindness, humility, gentleness and patience.", reference: "Colossians 3:12", task: "Pick one of these traits and practice it intentionally today."),
                Devotion(month: 12, day: 6, verse: "All those who exalt themselves will be humbled…", reference: "Luke 14:11", task: "Reflect: Where have you sought praise? Pray for a heart shift to serve, not show."),
                Devotion(month: 12, day: 7, verse: "Honor one another above yourselves.", reference: "Romans 12:10", task: "Send a text or note honoring someone else’s character or effort."),
                Devotion(month: 12, day: 8, verse: "The fruit of the Spirit is love, joy, peace, patience, kindness…", reference: "Galatians 5:22–23", task: "Do a “fruit check.” Which fruit are you lacking today? Ask God to grow it in you."),
                Devotion(month: 12, day: 9, verse: "What does the Lord require of you? To act justly, love mercy, and walk humbly.", reference: "Micah 6:8", task: "Choose mercy over judgment in one interaction today."),
                Devotion(month: 12, day: 10, verse: "Humble yourselves… that He may lift you up.", reference: "1 Peter 5:6", task: "Surrender an area where you're trying to “lift yourself.” Let God take over."),
                Devotion(month: 12, day: 11, verse: "Let your light shine before others… that they may glorify your Father.", reference: "Matthew 5:16", task: "Do one good deed in secret today — let God get the glory."),
                Devotion(month: 12, day: 12, verse: "Do not conform to the pattern of this world, but be transformed...", reference: "Romans 12:2", task: "Identify one “worldly pattern” you've been conforming to. Take a step back from it."),
                Devotion(month: 12, day: 13, verse: "I am gentle and humble in heart.", reference: "Matthew 11:29", task: "Practice gentleness in one conversation that would normally frustrate you."),
                Devotion(month: 12, day: 14, verse: "Be completely humble and gentle; be patient, bearing with one another in love.", reference: "Ephesians 4:2", task: "Today, choose patience. Slow down intentionally in traffic, conversations, or decisions."),
                Devotion(month: 12, day: 15, verse: "Be careful not to practice your righteousness in front of others to be seen.", reference: "Matthew 6:1", task: "Serve quietly today — no social media, no applause. Just for God."),
                Devotion(month: 12, day: 16, verse: "I am among you as one who serves.", reference: "Luke 22:27", task: "Find a simple way to serve someone close to you. Don’t wait — act today."),
                Devotion(month: 12, day: 17, verse: "He guides the humble in what is right and teaches them his way.", reference: "Psalm 25:9", task: "Ask God: “What do You want to teach me today?” Listen. Write it down."),
                Devotion(month: 12, day: 18, verse: "With humility comes wisdom.", reference: "Proverbs 11:2", task: "Read one chapter of Proverbs. Ask God for wisdom in one area you’re struggling in."),
                Devotion(month: 12, day: 19, verse: "He must become greater; I must become less.", reference: "John 3:30", task: "Reflect: Where are you trying to be the center? Pray for God to increase."),
                Devotion(month: 12, day: 20, verse: "Humble yourselves before the Lord, and he will lift you up.", reference: "James 4:10", task: "Bow physically today as you pray. Acknowledge God’s greatness over your life."),
                Devotion(month: 12, day: 21, verse: "These are the ones I look on with favor: those who are humble and contrite.", reference: "Isaiah 66:2", task: "Confess something to God you’ve been hiding. Let humility cleanse you."),
                Devotion(month: 12, day: 22, verse: "Let the one who boasts boast in the Lord.", reference: "2 Corinthians 10:17–18", task: "Share a testimony today — but make it about God’s greatness, not your own."),
                Devotion(month: 12, day: 23, verse: "Those who humble themselves will be exalted.", reference: "Matthew 23:12", task: "Reflect on a time God honored your humility. Thank Him for it."),
                Devotion(month: 12, day: 24, verse: "Forgive as the Lord forgave you.", reference: "Colossians 3:13", task: "Forgive someone who doesn’t deserve it — just like Christ did for you."),
                Devotion(month: 12, day: 25, verse: "Do nothing out of selfish ambition or vain conceit.", reference: "Philippians 2:3", task: "In one decision today, choose selflessness over personal gain."),
                Devotion(month: 12, day: 26, verse: "Do not merely listen to the word… do what it says.", reference: "James 1:22", task: "Apply one verse from this week. Live it out in a specific way."),
                Devotion(month: 12, day: 27, verse: "Let us not become weary in doing good.", reference: "Galatians 6:9", task: "Serve someone again — even if you’re tired, unnoticed, or unthanked."),
                Devotion(month: 12, day: 28, verse: "Take up your cross daily and follow Me.", reference: "Luke 9:23", task: "Sacrifice one comfort today to focus more on Christ."),
                Devotion(month: 12, day: 29, verse: "Offer your bodies as a living sacrifice...", reference: "Romans 12:1", task: "Fast one meal or distraction today. Offer that time to God."),
                Devotion(month: 12, day: 30, verse: "Whoever claims to live in Him must live as Jesus did.", reference: "1 John 2:6", task: "Actively ask yourself: “Does this reflect Jesus?” before any major action today."),
                Devotion(month: 12, day: 31, verse: "Anyone who wants to be first must be the very last, and the servant of all.", reference: "Mark 9:35", task: "End the month by asking: “How can I serve today?” Then go and do it.")
            ]
        }
